name: CI/CD Docker Java

on:
  push:
    branches: [ main ]   # déclencher le pipeline à chaque push sur main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupèrer le code source
      - name: Checkout du code
        uses: actions/checkout@v3

      # 2️⃣ Afficher le contenu du répertoire /app (ou /)
      - name: Afficher contenu du répertoire
        run: |
          echo "=== Vérification du répertoire ==="
          if [ -d "/app" ]; then
            ls -al /app
          else
            ls -al /
          fi

      # 3️⃣ Connexion à Docker Hub
      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Construction de l’image Docker
      - name: Construire l’image Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/a18_hamzamecheri_final_1288:latest .

      # 5️⃣ Envoi sur Docker Hub
      - name: Pousser l’image sur Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/a18_hamzamecheri_final_1288:latest